#!/bin/bash

SOURCE=`dirname $0`
SAMPLE=`cd "$SOURCE"/..; pwd -P`
BASE=`cd "$SAMPLE"/../../..; pwd -P`
AKKA_HOME="$BASE/akka"

[ -n "$JAVA_OPTS" ] || JAVA_OPTS="-Xmx512M"

# create the classpath
if [ -z "$SAMPLE_CLASSPATH" ] ; then
    SAMPLE_CLASSPATH="$BASE/scala/lib/scala-library.jar"
    for jar in "$AKKA_HOME"/lib/* ; do
        SAMPLE_CLASSPATH="$SAMPLE_CLASSPATH:$jar"
    done
    for jar in "$SAMPLE"/lib/* ; do
        SAMPLE_CLASSPATH="$SAMPLE_CLASSPATH:$jar"
    done
fi

java $JAVA_OPTS -cp "$SAMPLE_CLASSPATH" -Dakka.home="$SAMPLE" akka.kernel.Main
