#!/bin/bash

SAMPLE="$(cd "$(cd "$(dirname "$0")"; pwd -P)"/..; pwd)"

AKKA_HOME="$(cd "$SAMPLE"/../..; pwd)"

[ -n "$JAVA_OPTS" ] || JAVA_OPTS="-Xmx512M"

[ -n "$AKKA_CLASSPATH" ] || AKKA_CLASSPATH="$AKKA_HOME/lib/*"

SAMPLE_CLASSPATH="$AKKA_CLASSPATH:$SAMPLE/lib/*"

java $JAVA_OPTS -cp "$SAMPLE_CLASSPATH" -Dakka.home="$SAMPLE" akka.kernel.Main
